

CREATE TABLE "post_tags" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
"posts_id" INTEGER NOT NULL,
"tags_id" INTEGER NOT NULL,
FOREIGN KEY ("posts_id") REFERENCES "posts"("id") ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY ("tags_id") REFERENCES "tags"("id") ON UPDATE CASCADE ON DELETE CASCADE

);


CREATE TABLE "posts" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"contents" TEXT,
"data" TEXT,
"date" INTEGER NOT NULL,
"date_day" INTEGER NOT NULL,
"date_month" INTEGER NOT NULL,
"date_year" INTEGER NOT NULL,
"draft" INTEGER NOT NULL,
"hash" TEXT NOT NULL,
"homepage" INTEGER NOT NULL DEFAULT 0,
"last_updated" INTEGER NOT NULL,
"page" INTEGER NOT NULL DEFAULT 0,
"source_path" TEXT NOT NULL,
"section" TEXT,
"slug" TEXT NOT NULL,
"title" TEXT NOT NULL,
"url" TEXT NOT NULL,
"verified" INTEGER DEFAULT 0 NOT NULL
);


CREATE TABLE "tags" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
"name" TEXT NOT NULL UNIQUE
);
